# Generated by Django 5.0.1 on 2024-02-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_state_alter_orderplaced_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='order_date',
            new_name='ordered_date',
        ),
    ]
